const goods = [
  {
    "id": 1,
    "name": ".01 Elastic Warm",
    "desc": `This model embodies Parisian chic with an all-black ensemble that merges minimalism and grunge. The ribbed-knit sweater, both cozy and structured, exudes sophistication and effortless style. Paired with tailored joggers, it strikes a balance between streetwear and high fashion. A sleek black handbag with gold accents adds timeless elegance, while a minimalist watch symbolizes precision and refinement. Vintage-inspired sneakers contrast the dark outfit, blending grunge with haute couture. Her relaxed pose, lost in thought, evokes a modern Parisian, stylish, effortlessly captivating. Whether in a café on Rue Saint-Honoré or exploring the city, her look makes a statement without words. This isn’t just an outfit. It’s an identity.`,
    "imgpath": "/img/1.jpg",
    "number": ".01",
    "cost": "$3,999.00",
    "costper": "$333.25",
    "collection": "Autumn-Winter 2024",
    "type": "Sweater",
    "style": "Black Suite",
    "series": "Vatour",
    "sizeOnModel": "48",
    "explicit": "No",
    "sleeveType": "Middle",
    "features": "Warm & stylish",
    "brand": "Sylution",
    "rules": ["/laundry/1.jpg", "/laundry/10.jpg", "/laundry/9.jpg", "/laundry/13.jpg"]
  },
  {
    "id": 2,
    "name": ".02 Ghostity",
    "desc": `An ode to minimalisme raffiné, this monochrome ensemble radiates quiet sophistication. The oversized ivory sweater, soft and fluid, embodies both coziness and contemporary style. Tucked into high-waisted jeans, the contrast of textures creates visual harmony, emphasizing an effortlessly polished look. The structured belt cinches the waist, adding a hint of savoir-faire. This ensemble whispers of Parisian mornings, where style is instinctive yet intentional. Perfect for those who embrace l'élégance naturelle, this outfit is a versatile statement—whether for a casual coffee date or a day of creative inspiration. A tribute to le chic intemporel, where simplicity meets undeniable allure.`,
    "imgpath": "/img/2.jpg",
    "number": ".02",
    "cost": "$4,250.00",
    "costper": "$400.75",
    "collection": "Autumn-Winter 2025",
    "type": "Sweater",
    "style": "White Pre-over",
    "series": "Ghost",
    "sizeOnModel": "50",
    "explicit": "No",
    "sleeveType": "Spacious",
    "features": "Sexy & roomy",
    "brand": "Lethrone",
    "rules": ["/laundry/3.jpg", "/laundry/6.jpg", "/laundry/9.jpg", "/laundry/15.jpg"]
  },
  {
    "id": 3,
    "name": ".03 Le Simple",
    "desc": `A pristine ivory knit sweater, oversized and fluid, embodies l'élégance sans effort. The asymmetrical hemline introduces a contemporary edge, balancing structure and movement. The ribbed texture adds a tactile depth, elevating a simple silhouette into an artful expression of modern minimalism. Worn over black tailored pants, the look is a masterclass in refined contrast, merging confort absolu with chic sophistication. The slightly elongated sleeves hint at a nonchalant, undone appeal—perfect for those who adore la mode instinctive. Whether styled for a laid-back afternoon or a polished city ensemble, this piece captures the essence of timeless, effortless grace.`,
    "imgpath": "/img/3.jpg",
    "number": ".03",
    "cost": "$1,999.50",
    "costper": "$200.15",
    "collection": "Spring-Summer 2024",
    "type": "Light sweater",
    "style": "White Suite",
    "series": "Vatour",
    "sizeOnModel": "48",
    "explicit": "No",
    "sleeveType": "Long & Spacious",
    "features": "Easywear, Wash&Dry",
    "brand": "Sylution",
    "rules": ["/laundry/2.jpg", "/laundry/11.jpg", "/laundry/6.jpg", "/laundry/18.jpg"]
  },
  {
    "id": 4,
    "name": ".04 Sueverinne",
    "desc": `A delicately ribbed, buttoned cardigan in soft ivory—this piece is the epitome of délicatesse moderne. The fitted silhouette hugs the figure gracefully, blending comfort with an air of polished refinement. The subtle sheen of the fabric enhances its luxurious appeal, making it an ideal choice for les amoureuses du chic minimaliste. High-rise denim completes the ensemble, offering a contrast of structure and softness that embodies the essence of Parisian nonchalance. Perfect for casual brunches or spontaneous city adventures, this look defines la simplicité sophistiquée, where timeless elegance meets everyday ease in the most charming way.`,
    "imgpath": "/img/4.jpg",
    "number": ".04",
    "cost": "$2,799.50",
    "costper": "$250.25",
    "collection": "Summer-Autumn 2023",
    "type": "Short cardigan",
    "style": "Light",
    "series": "Evolve ©",
    "sizeOnModel": "46",
    "explicit": "No",
    "sleeveType": "Short",
    "features": "Soft & Stylish",
    "brand": "Cardistyle",
    "rules": ["/laundry/17.jpg", "/laundry/16.jpg", "/laundry/15.jpg", "/laundry/11.jpg"]
  },
  {
    "id": 5,
    "name": ".05 Create MFE",
    "desc": `A celebration of le chic décontracté, this ensemble fuses urban cool with timeless femininity. An oversized heather-gray sweatshirt falls effortlessly over a flowing midi skirt, creating a stunning balance of volume and grace. The relaxed fit ensures ultimate comfort, while the embroidered detail adds a subtle hint of raffinement discret. Paired with classic sneakers, this outfit captures the spirit of contemporary Parisian streetwear—where ease meets l'élégance naturelle. Ideal for city strolls, creative meetups, or cozy café mornings, this look speaks to those who embrace l’art du casual chic with an undeniable touch of sophistication.`,
    "imgpath": "/img/5.jpg",
    "number": ".05",
    "cost": "$2,999.00",
    "costper": "$250.99",
    "collection": "Winter-Winter 2025",
    "type": "Sweatshirt",
    "style": "Gray oversize",
    "series": "cafe.",
    "sizeOnModel": "52",
    "explicit": "No",
    "sleeveType": "Spacious",
    "features": "Warm & spacious",
    "brand": "Easeset",
    "rules": ["/laundry/17.jpg", "/laundry/16.jpg", "/laundry/15.jpg", "/laundry/11.jpg"]
  },
  {
    "id": 6,
    "name": ".06 Deep Olive",
    "desc": `Draped in a luxurious olive-green ribbed sweater, this look epitomizes élégance décontractée with a touch of Parisian charm. The deep earthy hue harmonizes beautifully with the soft texture of the knit, creating an inviting feel of douceur. The voluminous sleeves add a modern twist, exuding confidence and relaxed sophistication. Paired with tailored black trousers, this ensemble bridges casual chic with refined simplicity. A structured leather bag completes the outfit, adding a touche de luxe discret. Whether strolling through a fall-kissed city or enjoying a quiet café moment, this look celebrates l'authenticité of effortless style and comfort with impeccable finesse.`,
    "imgpath": "/img/6.jpg",
    "number": ".06",
    "cost": "$3,159.55",
    "costper": "$300.00",
    "collection": "Autumn-Winter 2025",
    "type": "Sweater",
    "style": "Olive Pre-over",
    "series": "Ghost",
    "sizeOnModel": "48",
    "explicit": "No",
    "sleeveType": "Middle",
    "features": "Skinny & Tight",
    "brand": "Sylution",
    "rules": ["/laundry/11.jpg", "/laundry/13.jpg", "/laundry/16.jpg", "/laundry/15.jpg"]
  },
];

export default goods;
